---
- name: This sets up an httpd webserver
  hosts: centos-02-vm
  #become: yes
  gather_facts: no
  tasks:
  - name: Creating an empty file
    file:
      path: "/var/file-created-with-ansible-newww"
      state: touch
  - name: cat a file 
    command: hostname
    register: result

  - debug:
      var: result
      verbosity: 2
