---
# - hosts: localhost
#   gather_facts: no
#   vars:
#     project: "logical-cubist-348810"
#   tasks:
#   - name: cating a file from awx machine that is Ansible AWX VM
#     command: cat /home/arf9983/ansible-gcp-demo/part1_create_vm.sh
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: logical-cubist-348810
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/arf9983/gcp-sa.json #/home/my_account.json
      zone: "us-central1-a"
      region: "us-central1"
  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 50
         source_image: 'projects/rocky-linux-cloud/global/images/rocky-linux-8-v20220126'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
