---
- hosts: localhost
  gather_facts: no
  vars:
    project: "logical-cubist-348810"
  tasks:
  – name: create a network
    gcp_compute_network:
      name: ansible-network
      auto_create_subnetworks: yes
      # project: "{{ lookup('env','GCP_PROJECT') }}"/
      project: "logical-cubist-348810"
      state: present
    register: network
